



//seedProductDetails.js

require("dotenv").config();

const connectDB = require("./config/db");
const ProductDetails = require("./models/productDetailsModel");

const details = [

 {
    productId: 1,
    scientificName: "Rosa hybrida",
    family: "Rosaceae",
    origin: "Asia",
    plantType: "Flowering Shrub",
    sunlight: "Full Sun",
    watering: "2–3 times per week",
    temperature: "15–30°C",
    humidity: "40–60%",
    soilType: "Well-drained Loamy Soil",
    growthRate: "Moderate",
    floweringSeason: "Spring to Autumn",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Medium",
    height: "1–2 meters",
    lifespan: "15+ years",
    description: "Hybrid Tea Rose is a beautiful ornamental flowering shrub admired for its large, colorful, and fragrant blooms. It thrives in sunny locations with well-drained soil."
},

{
    productId: 2,
    scientificName: "Monstera deliciosa",
    family: "Araceae",
    origin: "Central America",
    plantType: "Evergreen Tropical Plant",
    sunlight: "Bright Indirect Light",
    watering: "Once per week",
    temperature: "18–27°C",
    humidity: "60–80%",
    soilType: "Well-draining Potting Mix",
    growthRate: "Moderate",
    floweringSeason: "Rare Indoors",
    toxicity: "Toxic if ingested",
    petFriendly: false,
    difficulty: "Easy",
    height: "2–3 meters",
    lifespan: "20+ years",
    description: "Monstera deliciosa is a tropical evergreen plant famous for its large split leaves. It is one of the world's most popular indoor houseplants."
},

{
    productId: 3,
    scientificName: "Dracaena trifasciata",
    family: "Asparagaceae",
    origin: "West Africa",
    plantType: "Succulent Houseplant",
    sunlight: "Low to Bright Indirect Light",
    watering: "Every 2–3 weeks",
    temperature: "18–30°C",
    humidity: "30–60%",
    soilType: "Well-draining Sandy Soil",
    growthRate: "Slow",
    floweringSeason: "Rare Indoors",
    toxicity: "Toxic if ingested",
    petFriendly: false,
    difficulty: "Very Easy",
    height: "0.5–1.2 meters",
    lifespan: "25+ years",
    description: "Snake Plant is a hardy indoor plant known for its upright leaves and exceptional tolerance to low light and irregular watering."
},

{
    productId: 4,
    scientificName: "Spathiphyllum",
    family: "Araceae",
    origin: "Central and South America",
    plantType: "Flowering Houseplant",
    sunlight: "Bright Indirect Light",
    watering: "Once per week",
    temperature: "18–27°C",
    humidity: "50–70%",
    soilType: "Rich Well-drained Soil",
    growthRate: "Moderate",
    floweringSeason: "Spring and Summer",
    toxicity: "Toxic if ingested",
    petFriendly: false,
    difficulty: "Easy",
    height: "0.5–1 meter",
    lifespan: "10+ years",
    description: "Peace Lily is an elegant indoor plant with glossy green leaves and beautiful white flowers that brighten interior spaces."
},

{
    productId: 5,
    scientificName: "Zamioculcas zamiifolia",
    family: "Araceae",
    origin: "Eastern Africa",
    plantType: "Evergreen Houseplant",
    sunlight: "Low to Bright Indirect Light",
    watering: "Every 2 weeks",
    temperature: "18–30°C",
    humidity: "40–60%",
    soilType: "Well-draining Potting Mix",
    growthRate: "Slow",
    floweringSeason: "Rare Indoors",
    toxicity: "Toxic if ingested",
    petFriendly: false,
    difficulty: "Very Easy",
    height: "0.6–1 meter",
    lifespan: "15+ years",
    description: "ZZ Plant is a resilient indoor plant with glossy dark green leaves that requires minimal maintenance."
},

{
    productId: 6,
    scientificName: "Ficus elastica",
    family: "Moraceae",
    origin: "South Asia",
    plantType: "Evergreen Tree",
    sunlight: "Bright Indirect Light",
    watering: "Once per week",
    temperature: "18–28°C",
    humidity: "50–70%",
    soilType: "Well-draining Potting Soil",
    growthRate: "Moderate",
    floweringSeason: "Rare Indoors",
    toxicity: "Toxic if ingested",
    petFriendly: false,
    difficulty: "Easy",
    height: "2–3 meters",
    lifespan: "20+ years",
    description: "Rubber Plant is a popular ornamental indoor tree admired for its thick glossy leaves and elegant appearance."
},

{
    productId: 7,
    scientificName: "Dypsis lutescens",
    family: "Arecaceae",
    origin: "Madagascar",
    plantType: "Palm",
    sunlight: "Bright Indirect Light",
    watering: "Once per week",
    temperature: "20–30°C",
    humidity: "50–70%",
    soilType: "Well-draining Soil",
    growthRate: "Moderate",
    floweringSeason: "Rare Indoors",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "2–4 meters",
    lifespan: "15+ years",
    description: "Areca Palm is a graceful tropical palm that adds a lush and relaxing atmosphere to homes and offices."
},

{
    productId: 8,
    scientificName: "Epipremnum aureum",
    family: "Araceae",
    origin: "French Polynesia",
    plantType: "Trailing Vine",
    sunlight: "Low to Bright Indirect Light",
    watering: "Once per week",
    temperature: "18–30°C",
    humidity: "50–70%",
    soilType: "Well-draining Potting Mix",
    growthRate: "Fast",
    floweringSeason: "Rare Indoors",
    toxicity: "Toxic if ingested",
    petFriendly: false,
    difficulty: "Very Easy",
    height: "Up to 10 meters",
    lifespan: "10+ years",
    description: "Golden Pothos is one of the easiest houseplants to grow and is loved for its attractive trailing vines."
},

{
    productId: 9,
    scientificName: "Ficus lyrata",
    family: "Moraceae",
    origin: "Western Africa",
    plantType: "Indoor Tree",
    sunlight: "Bright Indirect Light",
    watering: "Once per week",
    temperature: "18–27°C",
    humidity: "50–70%",
    soilType: "Well-draining Soil",
    growthRate: "Moderate",
    floweringSeason: "Rare Indoors",
    toxicity: "Toxic if ingested",
    petFriendly: false,
    difficulty: "Medium",
    height: "2–3 meters",
    lifespan: "20+ years",
    description: "Fiddle Leaf Fig is a premium ornamental tree recognized for its large violin-shaped leaves and modern decorative appeal."
},

{
    productId: 10,
    scientificName: "Aglaonema",
    family: "Araceae",
    origin: "Southeast Asia",
    plantType: "Evergreen Houseplant",
    sunlight: "Low to Bright Indirect Light",
    watering: "Once per week",
    temperature: "18–30°C",
    humidity: "50–70%",
    soilType: "Rich Well-drained Soil",
    growthRate: "Slow",
    floweringSeason: "Rare Indoors",
    toxicity: "Toxic if ingested",
    petFriendly: false,
    difficulty: "Easy",
    height: "0.5–1 meter",
    lifespan: "10+ years",
    description: "Chinese Evergreen is appreciated for its colorful foliage and outstanding ability to tolerate low-light indoor conditions."
},

{
    productId: 11,
    scientificName: "Chlorophytum comosum",
    family: "Asparagaceae",
    origin: "South Africa",
    plantType: "Perennial Houseplant",
    sunlight: "Bright Indirect Light",
    watering: "Once per week",
    temperature: "18–27°C",
    humidity: "40–60%",
    soilType: "Well-draining Potting Soil",
    growthRate: "Fast",
    floweringSeason: "Spring and Summer",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Very Easy",
    height: "30–60 cm",
    lifespan: "20+ years",
    description: "Spider Plant is a classic indoor plant with arching striped leaves, famous for its easy care and rapid growth."
},


{
    productId: 12,
    scientificName: "Aloe vera",
    family: "Asphodelaceae",
    origin: "Arabian Peninsula",
    plantType: "Succulent",
    sunlight: "Full Sun to Bright Light",
    watering: "Every 2–3 weeks",
    temperature: "18–30°C",
    humidity: "30–50%",
    soilType: "Well-draining Cactus Soil",
    growthRate: "Moderate",
    floweringSeason: "Spring",
    toxicity: "Mildly toxic if ingested",
    petFriendly: false,
    difficulty: "Very Easy",
    height: "30–60 cm",
    lifespan: "15+ years",
    description: "Aloe Vera is a medicinal succulent famous for its soothing gel, commonly used in skincare and traditional medicine."
},

{
    productId: 13,
    scientificName: "Lavandula angustifolia",
    family: "Lamiaceae",
    origin: "Mediterranean Region",
    plantType: "Flowering Herb",
    sunlight: "Full Sun",
    watering: "Once per week",
    temperature: "15–30°C",
    humidity: "30–50%",
    soilType: "Well-draining Sandy Soil",
    growthRate: "Moderate",
    floweringSeason: "Summer",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "30–90 cm",
    lifespan: "10+ years",
    description: "Lavender is a fragrant herb valued for its beautiful purple flowers, calming scent, and essential oils."
},

{
    productId: 14,
    scientificName: "Mentha × piperita",
    family: "Lamiaceae",
    origin: "Europe",
    plantType: "Perennial Herb",
    sunlight: "Full Sun to Partial Shade",
    watering: "2–3 times per week",
    temperature: "15–28°C",
    humidity: "50–70%",
    soilType: "Moist Rich Soil",
    growthRate: "Fast",
    floweringSeason: "Summer",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "30–60 cm",
    lifespan: "5+ years",
    description: "Peppermint is a refreshing herb widely used for tea, cooking, and traditional medicinal purposes."
},

{
    productId: 15,
    scientificName: "Salvia rosmarinus",
    family: "Lamiaceae",
    origin: "Mediterranean Region",
    plantType: "Evergreen Herb",
    sunlight: "Full Sun",
    watering: "Once per week",
    temperature: "15–30°C",
    humidity: "30–50%",
    soilType: "Well-draining Sandy Soil",
    growthRate: "Moderate",
    floweringSeason: "Spring",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "1–2 meters",
    lifespan: "15+ years",
    description: "Rosemary is an aromatic evergreen herb appreciated for cooking, landscaping, and herbal remedies."
},

{
    productId: 16,
    scientificName: "Matricaria chamomilla",
    family: "Asteraceae",
    origin: "Europe and Western Asia",
    plantType: "Flowering Herb",
    sunlight: "Full Sun",
    watering: "Once per week",
    temperature: "15–25°C",
    humidity: "40–60%",
    soilType: "Well-draining Soil",
    growthRate: "Fast",
    floweringSeason: "Spring and Summer",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "20–60 cm",
    lifespan: "Annual",
    description: "Chamomile is a gentle flowering herb known for its calming properties and soothing herbal tea."
},

{
    productId: 17,
    scientificName: "Salvia officinalis",
    family: "Lamiaceae",
    origin: "Mediterranean Region",
    plantType: "Perennial Herb",
    sunlight: "Full Sun",
    watering: "Once per week",
    temperature: "15–30°C",
    humidity: "30–50%",
    soilType: "Well-draining Soil",
    growthRate: "Moderate",
    floweringSeason: "Spring",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "30–70 cm",
    lifespan: "10+ years",
    description: "Sage is a fragrant herb valued for culinary uses and its long history in traditional herbal medicine."
},

{
    productId: 18,
    scientificName: "Melissa officinalis",
    family: "Lamiaceae",
    origin: "Southern Europe",
    plantType: "Perennial Herb",
    sunlight: "Full Sun to Partial Shade",
    watering: "Twice per week",
    temperature: "15–28°C",
    humidity: "50–70%",
    soilType: "Rich Moist Soil",
    growthRate: "Fast",
    floweringSeason: "Summer",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "30–90 cm",
    lifespan: "10+ years",
    description: "Lemon Balm is a refreshing medicinal herb with a pleasant lemon fragrance, often used in herbal teas."
},

{
    productId: 19,
    scientificName: "Thymus vulgaris",
    family: "Lamiaceae",
    origin: "Mediterranean Region",
    plantType: "Perennial Herb",
    sunlight: "Full Sun",
    watering: "Once per week",
    temperature: "15–30°C",
    humidity: "30–50%",
    soilType: "Well-draining Sandy Soil",
    growthRate: "Moderate",
    floweringSeason: "Late Spring",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "20–40 cm",
    lifespan: "10+ years",
    description: "Thyme is an aromatic herb prized for its culinary flavor and traditional medicinal benefits."
},

{
    productId: 20,
    scientificName: "Ocimum tenuiflorum",
    family: "Lamiaceae",
    origin: "Indian Subcontinent",
    plantType: "Medicinal Herb",
    sunlight: "Full Sun",
    watering: "2–3 times per week",
    temperature: "20–35°C",
    humidity: "50–70%",
    soilType: "Rich Well-draining Soil",
    growthRate: "Fast",
    floweringSeason: "Summer",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "30–60 cm",
    lifespan: "5+ years",
    description: "Holy Basil (Tulsi) is a sacred medicinal herb widely recognized for its traditional wellness benefits."
},

{
    productId: 21,
    scientificName: "Origanum vulgare",
    family: "Lamiaceae",
    origin: "Mediterranean Region",
    plantType: "Perennial Herb",
    sunlight: "Full Sun",
    watering: "Once per week",
    temperature: "15–30°C",
    humidity: "30–50%",
    soilType: "Well-draining Soil",
    growthRate: "Moderate",
    floweringSeason: "Summer",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "30–80 cm",
    lifespan: "10+ years",
    description: "Oregano is a fragrant herb commonly used in cooking and appreciated for its antioxidant and medicinal properties."
},



{
    productId: 22,
    scientificName: "Solanum lycopersicum",
    family: "Solanaceae",
    origin: "South America",
    plantType: "Vegetable Seedling",
    sunlight: "Full Sun",
    watering: "2–3 times per week",
    temperature: "20–30°C",
    humidity: "50–70%",
    soilType: "Rich Well-draining Soil",
    growthRate: "Fast",
    floweringSeason: "Spring and Summer",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "1–2 meters",
    lifespan: "Annual",
    description: "Tomato seedlings develop into productive plants that produce juicy, flavorful tomatoes suitable for gardens and containers."
},

{
    productId: 23,
    scientificName: "Capsicum annuum",
    family: "Solanaceae",
    origin: "Central America",
    plantType: "Vegetable Seedling",
    sunlight: "Full Sun",
    watering: "2–3 times per week",
    temperature: "20–30°C",
    humidity: "50–70%",
    soilType: "Fertile Well-draining Soil",
    growthRate: "Moderate",
    floweringSeason: "Summer",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "50–100 cm",
    lifespan: "Annual",
    description: "Pepper seedlings grow into healthy plants capable of producing sweet or hot peppers depending on the variety."
},

{
    productId: 24,
    scientificName: "Cucumis sativus",
    family: "Cucurbitaceae",
    origin: "South Asia",
    plantType: "Vegetable Seedling",
    sunlight: "Full Sun",
    watering: "Frequent",
    temperature: "20–32°C",
    humidity: "60–80%",
    soilType: "Moist Fertile Soil",
    growthRate: "Fast",
    floweringSeason: "Summer",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "Climbing Vine",
    lifespan: "Annual",
    description: "Cucumber seedlings grow rapidly and produce crisp, refreshing cucumbers under warm growing conditions."
},

{
    productId: 25,
    scientificName: "Solanum melongena",
    family: "Solanaceae",
    origin: "India",
    plantType: "Vegetable Seedling",
    sunlight: "Full Sun",
    watering: "2–3 times per week",
    temperature: "22–32°C",
    humidity: "50–70%",
    soilType: "Rich Well-draining Soil",
    growthRate: "Moderate",
    floweringSeason: "Summer",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Medium",
    height: "60–120 cm",
    lifespan: "Annual",
    description: "Eggplant seedlings produce vigorous plants with glossy purple fruits and excellent yields."
},

{
    productId: 26,
    scientificName: "Lactuca sativa",
    family: "Asteraceae",
    origin: "Mediterranean Region",
    plantType: "Leafy Vegetable Seedling",
    sunlight: "Full Sun to Partial Shade",
    watering: "Frequent",
    temperature: "10–24°C",
    humidity: "50–70%",
    soilType: "Moist Fertile Soil",
    growthRate: "Fast",
    floweringSeason: "Spring",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Very Easy",
    height: "20–30 cm",
    lifespan: "Annual",
    description: "Lettuce seedlings quickly develop into leafy vegetables perfect for fresh salads."
},

{
    productId: 27,
    scientificName: "Brassica oleracea var. italica",
    family: "Brassicaceae",
    origin: "Italy",
    plantType: "Vegetable Seedling",
    sunlight: "Full Sun",
    watering: "Regular",
    temperature: "15–24°C",
    humidity: "50–70%",
    soilType: "Rich Well-draining Soil",
    growthRate: "Moderate",
    floweringSeason: "Spring",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "45–90 cm",
    lifespan: "Annual",
    description: "Broccoli seedlings grow into healthy plants producing nutritious green flower heads."
},

{
    productId: 28,
    scientificName: "Brassica oleracea var. capitata",
    family: "Brassicaceae",
    origin: "Europe",
    plantType: "Vegetable Seedling",
    sunlight: "Full Sun",
    watering: "Regular",
    temperature: "15–24°C",
    humidity: "50–70%",
    soilType: "Rich Moist Soil",
    growthRate: "Moderate",
    floweringSeason: "Spring",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "30–60 cm",
    lifespan: "Annual",
    description: "Cabbage seedlings develop into compact leafy heads suitable for home gardens and farms."
},

{
    productId: 29,
    scientificName: "Fragaria × ananassa",
    family: "Rosaceae",
    origin: "Europe",
    plantType: "Fruit Seedling",
    sunlight: "Full Sun",
    watering: "Regular",
    temperature: "15–26°C",
    humidity: "50–70%",
    soilType: "Well-draining Slightly Acidic Soil",
    growthRate: "Moderate",
    floweringSeason: "Spring",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "20–30 cm",
    lifespan: "3–5 years",
    description: "Strawberry seedlings produce sweet red berries and are ideal for gardens, raised beds, and containers."
},

{
    productId: 30,
    scientificName: "Citrullus lanatus",
    family: "Cucurbitaceae",
    origin: "Africa",
    plantType: "Fruit Seedling",
    sunlight: "Full Sun",
    watering: "Frequent",
    temperature: "22–35°C",
    humidity: "50–70%",
    soilType: "Sandy Well-draining Soil",
    growthRate: "Fast",
    floweringSeason: "Summer",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Medium",
    height: "Trailing Vine",
    lifespan: "Annual",
    description: "Watermelon seedlings develop into vigorous vines capable of producing large, sweet, juicy fruits."
},

{
    productId: 31,
    scientificName: "Cucurbita pepo",
    family: "Cucurbitaceae",
    origin: "Central America",
    plantType: "Vegetable Seedling",
    sunlight: "Full Sun",
    watering: "Regular",
    temperature: "20–32°C",
    humidity: "50–70%",
    soilType: "Rich Well-draining Soil",
    growthRate: "Fast",
    floweringSeason: "Summer",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "Trailing Vine",
    lifespan: "Annual",
    description: "Zucchini seedlings grow quickly and produce abundant tender fruits throughout the growing season."
},






{
    productId: 32,
    scientificName: "Helianthus annuus",
    family: "Asteraceae",
    origin: "North America",
    plantType: "Flower Seeds",
    sunlight: "Full Sun",
    watering: "Moderate",
    temperature: "18–30°C",
    humidity: "40–60%",
    soilType: "Well-draining Soil",
    growthRate: "Fast",
    floweringSeason: "Summer",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "1.5–3 meters",
    lifespan: "Annual",
    description: "Sunflower seeds produce tall flowering plants with bright yellow blooms that attract pollinators."
},

{
    productId: 33,
    scientificName: "Solanum lycopersicum",
    family: "Solanaceae",
    origin: "South America",
    plantType: "Vegetable Seeds",
    sunlight: "Full Sun",
    watering: "Regular",
    temperature: "20–30°C",
    humidity: "50–70%",
    soilType: "Rich Well-draining Soil",
    growthRate: "Fast",
    floweringSeason: "Summer",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "1–2 meters",
    lifespan: "Annual",
    description: "Tomato seeds offer excellent germination and produce healthy plants with abundant fruits."
},

{
    productId: 34,
    scientificName: "Capsicum annuum",
    family: "Solanaceae",
    origin: "Central America",
    plantType: "Vegetable Seeds",
    sunlight: "Full Sun",
    watering: "Regular",
    temperature: "20–30°C",
    humidity: "50–70%",
    soilType: "Fertile Soil",
    growthRate: "Moderate",
    floweringSeason: "Summer",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "50–100 cm",
    lifespan: "Annual",
    description: "Pepper seeds develop into productive plants suitable for sweet or hot pepper cultivation."
},

{
    productId: 35,
    scientificName: "Cucumis sativus",
    family: "Cucurbitaceae",
    origin: "South Asia",
    plantType: "Vegetable Seeds",
    sunlight: "Full Sun",
    watering: "Frequent",
    temperature: "20–32°C",
    humidity: "60–80%",
    soilType: "Moist Fertile Soil",
    growthRate: "Fast",
    floweringSeason: "Summer",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "Climbing Vine",
    lifespan: "Annual",
    description: "Cucumber seeds produce vigorous vines with crisp, refreshing fruits."
},

{
    productId: 36,
    scientificName: "Citrullus lanatus",
    family: "Cucurbitaceae",
    origin: "Africa",
    plantType: "Fruit Seeds",
    sunlight: "Full Sun",
    watering: "Regular",
    temperature: "22–35°C",
    humidity: "50–70%",
    soilType: "Sandy Well-draining Soil",
    growthRate: "Fast",
    floweringSeason: "Summer",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Medium",
    height: "Trailing Vine",
    lifespan: "Annual",
    description: "Watermelon seeds produce vigorous vines with large sweet fruits under warm conditions."
},

{
    productId: 37,
    scientificName: "Lactuca sativa",
    family: "Asteraceae",
    origin: "Mediterranean Region",
    plantType: "Leafy Vegetable Seeds",
    sunlight: "Full Sun to Partial Shade",
    watering: "Frequent",
    temperature: "10–24°C",
    humidity: "50–70%",
    soilType: "Moist Rich Soil",
    growthRate: "Fast",
    floweringSeason: "Spring",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Very Easy",
    height: "20–30 cm",
    lifespan: "Annual",
    description: "Lettuce seeds germinate quickly and produce fresh leafy vegetables perfect for salads."
},

{
    productId: 38,
    scientificName: "Daucus carota",
    family: "Apiaceae",
    origin: "Central Asia",
    plantType: "Root Vegetable Seeds",
    sunlight: "Full Sun",
    watering: "Regular",
    temperature: "15–25°C",
    humidity: "50–70%",
    soilType: "Loose Sandy Soil",
    growthRate: "Moderate",
    floweringSeason: "Spring",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "30–60 cm",
    lifespan: "Biennial",
    description: "Carrot seeds produce sweet, nutritious roots in loose fertile soil."
},

{
    productId: 39,
    scientificName: "Zea mays",
    family: "Poaceae",
    origin: "Mexico",
    plantType: "Grain Seeds",
    sunlight: "Full Sun",
    watering: "Regular",
    temperature: "20–30°C",
    humidity: "50–70%",
    soilType: "Rich Well-draining Soil",
    growthRate: "Fast",
    floweringSeason: "Summer",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "2–3 meters",
    lifespan: "Annual",
    description: "Corn seeds produce vigorous plants with sweet, nutritious ears under sunny growing conditions."
},

{
    productId: 40,
    scientificName: "Phaseolus vulgaris",
    family: "Fabaceae",
    origin: "Central America",
    plantType: "Legume Seeds",
    sunlight: "Full Sun",
    watering: "Regular",
    temperature: "18–30°C",
    humidity: "50–70%",
    soilType: "Well-draining Soil",
    growthRate: "Fast",
    floweringSeason: "Summer",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "40 cm–2 meters",
    lifespan: "Annual",
    description: "Bean seeds grow rapidly and produce abundant nutritious pods throughout the season."
},

{
    productId: 41,
    scientificName: "Pisum sativum",
    family: "Fabaceae",
    origin: "Mediterranean Region",
    plantType: "Legume Seeds",
    sunlight: "Full Sun",
    watering: "Regular",
    temperature: "13–24°C",
    humidity: "50–70%",
    soilType: "Rich Well-draining Soil",
    growthRate: "Fast",
    floweringSeason: "Spring",
    toxicity: "Non-toxic",
    petFriendly: true,
    difficulty: "Easy",
    height: "0.5–2 meters",
    lifespan: "Annual",
    description: "Pea seeds produce climbing plants with tender green pods and excellent yields."
},







];

const seedData = async () => {

    try {

        await connectDB();

        await ProductDetails.deleteMany();

        await ProductDetails.insertMany(details);

        console.log("✅ Product details added successfully.");

        process.exit();

    } catch (error) {

        console.error(error);

        process.exit(1);

    }

};

seedData();